# Generated by Django 3.1.4 on 2020-12-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phishtank_id', models.IntegerField()),
                ('URL', models.CharField(max_length=100)),
                ('phish_detail_url', models.CharField(max_length=300)),
                ('submission_time', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('verification_time', models.DateField()),
                ('online', models.BooleanField(default=False)),
                ('target', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('cidr_block', models.CharField(max_length=50)),
                ('announcing_network', models.CharField(max_length=50)),
                ('rir', models.CharField(max_length=50)),
                ('detail_time', models.DateField()),
                ('confirmed_target', models.CharField(max_length=50)),
                ('tool_used', models.CharField(max_length=50)),
                ('is_referenced_google', models.BooleanField(default=False)),
                ('imported_since', models.DateField()),
            ],
        ),
    ]
