# Generated by Django 3.1.4 on 2020-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_stats',
            name='confirmed_target',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='imported_since',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='is_referenced_google',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='online',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='tool_used',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='verified',
            field=models.BooleanField(),
        ),
    ]
