# Generated by Django 3.1.4 on 2020-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0002_auto_20201221_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_stats',
            name='imported_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
