# Generated by Django 3.1.4 on 2020-12-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0004_history_global_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_global_stats',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
