# Generated by Django 3.1.4 on 2020-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0005_auto_20201224_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_stats',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
