# Generated by Django 3.1.4 on 2020-12-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0006_global_stats_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_stats',
            name='files_found',
            field=models.BooleanField(default=False),
        ),
    ]
