# Generated by Django 3.1.4 on 2021-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0007_global_stats_files_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloaded_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField()),
                ('sha1_hex', models.CharField(max_length=40)),
                ('extension', models.CharField(max_length=10)),
                ('first_dl_date', models.DateTimeField()),
                ('last_dl_date', models.DateTimeField()),
                ('h_inspection_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
