# Generated by Django 3.1.4 on 2021-01-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0008_downloaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaded_file',
            name='sha1_is_not_same_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='downloaded_file',
            name='sha1_is_same_count',
            field=models.IntegerField(default=0),
        ),
    ]
