# Generated by Django 3.1.4 on 2021-01-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0009_auto_20210105_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaded_file',
            name='URL',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='URL',
            field=models.CharField(max_length=300),
        ),
    ]
