# Generated by Django 3.1.4 on 2021-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0010_auto_20210111_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_stats',
            name='announcing_network',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='cidr_block',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='detail_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='rir',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
