# Generated by Django 3.1.4 on 2021-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0011_auto_20210116_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_stats',
            name='announcing_network',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='cidr_block',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='detail_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='rir',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
