# Generated by Django 3.1.4 on 2021-01-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0012_auto_20210116_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_stats',
            old_name='country',
            new_name='location',
        ),
    ]
