# Generated by Django 3.1.4 on 2021-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0013_auto_20210118_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_stats',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
