# Generated by Django 3.1.4 on 2021-01-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0014_auto_20210118_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_stats',
            name='country',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
