# Generated by Django 3.1.4 on 2021-01-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0015_global_stats_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_stats',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='global_stats',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
