# Generated by Django 3.1.4 on 2021-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0017_downloaded_file_email_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaded_file',
            name='email_list',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
