# Generated by Django 3.1.4 on 2021-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webphis', '0019_global_stats_country_iso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_stats',
            old_name='location',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='global_stats',
            name='long',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
